### ISSUE TITLE
 document is not defined in universal-production_Angular 2. Help_Thanks

### ISSUE THREAD

**Issue by hannesalagoste** [ui-router/angular#148]
```
ReferenceError: document is not defined
    at prepareQueryCSS (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:13796)
    at MatchMedia._buildMQL (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:15861)
    at MatchMedia.registerQuery (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:15690)
    at /home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:3524
    at Array.forEach (native)
    at MediaMonitor._registerBreakpoints (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:3484)
    at new MediaMonitor (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:2058)
    at _createClass (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:48142)
    at _createProviderInstance$1 (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:47654)
    at resolveNgModuleDep (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:47412)
ERROR { Error: Uncaught (in promise): ReferenceError: window is not defined
ReferenceError: window is not defined
    at MatchMedia._buildMQL (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:15885)
    at MatchMedia.registerQuery (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:15690)
    at /home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:3524
    at Array.forEach (native)
    at MediaMonitor._registerBreakpoints (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:3484)
    at new MediaMonitor (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:2058)
    at _createClass (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:48142)
    at _createProviderInstance$1 (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:47654)
    at resolveNgModuleDep (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:47412)
    at NgModuleRef_.get (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:205853)
    at resolvePromise (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:1041183)
    at resolvePromise (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:1040529)
    at /home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:1042197
    at ZoneDelegate.invokeTask (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:1035689)
    at Object.onInvokeTask (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:23213)
    at ZoneDelegate.invokeTask (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:1035579)
    at Zone.runTask (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:1028351)
    at drainMicroTaskQueue (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:1024381)
    at ZoneTask.invokeTask (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:1037311)
    at ZoneTask.options.isUsingGlobalCallback.invoke (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:1037073)
  rejection: 
   { ReferenceError: window is not defined
       at MatchMedia._buildMQL (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:15885)
       at MatchMedia.registerQuery (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:15690)
       at /home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:3524
       at Array.forEach (native)
       at MediaMonitor._registerBreakpoints (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:3484)
       at new MediaMonitor (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:2058)
       at _createClass (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:48142)
       at _createProviderInstance$1 (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:47654)
       at resolveNgModuleDep (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:47412)
       at NgModuleRef_.get (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:205853)
     __zone_symbol__currentTask: 
      ZoneTask {
        _zone: [Object],
        runCount: 0,
        _zoneDelegates: null,
        _state: 'notScheduled',
        type: 'microTask',
        source: 'Promise.then',
        data: undefined,
        scheduleFn: undefined,
        cancelFn: null,
        callback: [Function],
        invoke: [Function] } },
  promise: 
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value: 
      { ReferenceError: window is not defined
          at MatchMedia._buildMQL (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:15885)
          at MatchMedia.registerQuery (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:15690)
          at /home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:3524
          at Array.forEach (native)
          at MediaMonitor._registerBreakpoints (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:3484)
          at new MediaMonitor (/home/hanne/WebstormProjects/projectx-frontend/.server/server.1.chunk.js:1:2058)
          at _createClass (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:48142)
          at _createProviderInstance$1 (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:47654)
          at resolveNgModuleDep (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:47412)
          at NgModuleRef_.get (/home/hanne/WebstormProjects/projectx-frontend/.server/server.js:1:205853) __zone_symbol__currentTask: [Object] } },
  zone: 
   Zone {
     _properties: { isAngularZone: true },
     _parent: 
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     _name: 'angular',
     _zoneDelegate: 
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [Object],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Object],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Object],
        _invokeZS: [Object],
        _invokeDlgt: [Object],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [Object],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [Object],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [Object],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [Object],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [Object],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task: 
   ZoneTask {
     _zone: 
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
```

**Comment by BlankHrt** [comment]
same problem. 
Have you solved it yet?

**Comment by christopherthielen** [comment]
I think this is a probably fixed by https://github.com/angular/flex-layout/pull/353 and is unrelated to ui-router
