### ISSUE TITLE
Angular 5.1 + Universal. Error: No component factory found for UIView

### ISSUE THREAD

**Issue by atmman9001** [ui-router/angular#189]
Hello.

It's impossible to use ui-router/angular in the project with the latest angular libraries (5.1.3) and SSR. When I run node app with SSR I get the error:

`ERROR { Error: No component factory found for UIView. Did you add it to @NgModule.entryComponents?
    at ZoneAwareError (/Users/artemshtanko/Projects/ui-router-sample-app-angular-fork/dist/server.js:124658:33)
    at noComponentFactoryError (/Users/artemshtanko/Projects/ui-router-sample-app-angular-fork/dist/server.js:5354:34)
    at CodegenComponentFactoryResolver.resolveComponentFactory (/Users/artemshtanko/Projects/ui-router-sample-app-angular-fork/dist/server.js:5418:19)
    at ApplicationRef.bootstrap (/Users/artemshtanko/Projects/ui-router-sample-app-angular-fork/dist/server.js:7303:67)
    at /Users/artemshtanko/Projects/ui-router-sample-app-angular-fork/dist/server.js:7038:81
    at Array.forEach (<anonymous>)
    at PlatformRef._moduleDoBootstrap (/Users/artemshtanko/Projects/ui-router-sample-app-angular-fork/dist/server.js:7038:44)
    at /Users/artemshtanko/Projects/ui-router-sample-app-angular-fork/dist/server.js:6959:27
    at ZoneDelegate.invoke (/Users/artemshtanko/Projects/ui-router-sample-app-angular-fork/dist/server.js:124106:26)
    at Object.onInvoke (/Users/artemshtanko/Projects/ui-router-sample-app-angular-fork/dist/server.js:6209:33)
    at ZoneDelegate.invoke (/Users/artemshtanko/Projects/ui-router-sample-app-angular-fork/dist/server.js:124105:32)
    at Zone.run (/Users/artemshtanko/Projects/ui-router-sample-app-angular-fork/dist/server.js:123866:43)
    at /Users/artemshtanko/Projects/ui-router-sample-app-angular-fork/dist/server.js:124501:57
    at ZoneDelegate.invokeTask (/Users/artemshtanko/Projects/ui-router-sample-app-angular-fork/dist/server.js:124139:31)
    at Object.onInvokeTask (/Users/artemshtanko/Projects/ui-router-sample-app-angular-fork/dist/server.js:6200:33)
`

I've forked your sample app and updated libs. Please check it here:
https://github.com/atmman9001/sample-app-angular/tree/angular-universal

The branch is angular-universal.

Please fetch the repository, switch to `angular-universal` branch. Then run `yarn` and `npm run build:dynamic && npm run serve:dynamic`.

After that please open in the browser or make a GET request to http://localhost:4000/

You'll see error in the console.

Thanks.

**Comment by atmman9001** [comment]
@christopherthielen Could you please tell me did you check it? Do you have any updates?

**Comment by atmman9001** [comment]
@aitboudad Could you please check it too? I saw that you worked on the SSR with ui-router

**Comment by atmman9001** [comment]
Any updates here?

**Comment by atmman9001** [comment]
@christopherthielen @aitboudad - I've tested the problem with the latest ui-router and angular libs, and the ui-router still have the issue with server side rendering. I pushed updates for the package.json and yarn.lock files to my repo for reproducing. Could you please check it?

**Comment by christopherthielen** [comment]
I switched the bootstrap component from a `UIView` to a custom component and it seems to work now:  https://github.com/atmman9001/sample-app-angular/pull/1/files


```
import { Component } from '@angular/core';

@Component({
  selector: 'sample-app-root',
  template: `<ui-view></ui-view>`
})
export class SampleAppRootComponent {
}
```

```
bootstrap: [SampleAppRootComponent],
```
