### ISSUE TITLE
"No NgModule metadata found" for lazy loaded module

### ISSUE THREAD

**Issue by lexigren** [ui-router/angular#24]
I'm trying to lazy load module Products
app.states.ts:
```
{
    name: 'Products',
    url: '/products',
    lazyLoad: loadProductsModule
  }
```

lazy.modules.ts:

```
export function loadProductsModule() {
  return loadNgModule(function () {
    return System.import('./views/products/products.module')
      .then(result => {
        return result.ProductsModule;
      });
  }, ExtraModuleInjector.injector);
}
```

0.chunk.js getting loaded successfully and System.import is getting resolved with object containing ProductsModule.

But next I'm getting an error: "No NgModule metadata found for '[object Object]"
With native router lazy load of same module works normally.

Could it be because of wrong scoped injector? 

> loadNgModule Gets the Injector (scoped properly for the destination state)

This one I'm getting from app.component from app module.
If I can't use this one, where should I take correct one? I couldn't find answer in docs.
Thank you.

**Comment by christopherthielen** [comment]
are you on the official `beta.3` build?  I [don't think `beta.3` supports](https://ui-router.github.io/ng2/docs/latest/modules/ng2.html#loadngmodule) the callback to `loadNgModule ` yet.

`beta.4` and `beta.5` are going to change ng module loading significantly.  stay tuned.

**Comment by yuxiaomin** [comment]
Hello, I am on the official beta.4 build and run into the same issue when I used the callback function to lazy load. 

Following the docs I also tried this way to lazy load the module
```
var stocksState = {
  name: 'stocks',
  url: '/stocks',
  lazyLoad: loadNgModule('stocks/client/components/app.module.child#ChildAppModule')
}
```

In the systemjs.config
I got this error
```
ui-router-ng2.js:6374 TransitionRejection(type: 6, message: The transition errored, detail: Error: DI Error)
$defaultErrorHandler @ ui-router-ng2.js:6374
(anonymous) @ ui-router-ng2.js:6706
e.invoke @ zone.min.js:1
onInvoke @ core.umd.js:4427
e.invoke @ zone.min.js:1
t.run @ zone.min.js:1
(anonymous) @ zone.min.js:1
e.invokeTask @ zone.min.js:1
onInvokeTask @ core.umd.js:4418
e.invokeTask @ zone.min.js:1
t.runTask @ zone.min.js:1
a @ zone.min.js:1
invoke @ zone.min.js:1
ui-router-ng2.js:6376 Error: DI Error
    at NoProviderError.d (http://localhost:3000/vendor/zonejs/dist/zone.min.js:1:11171)
    at NoProviderError.BaseError [as constructor] (http://localhost:3000/vendor/@angular/core/bundles/core.umd.js:1186:20)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:3000/vendor/@angular/core/bundles/core.umd.js:1371:20)
    at new NoProviderError (http://localhost:3000/vendor/@angular/core/bundles/core.umd.js:1411:20)
    at ReflectiveInjector_._throwOrNull (http://localhost:3000/vendor/@angular/core/bundles/core.umd.js:3394:23)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:3000/vendor/@angular/core/bundles/core.umd.js:3433:29)
    at ReflectiveInjector_._getByKey (http://localhost:3000/vendor/@angular/core/bundles/core.umd.js:3380:29)
    at ReflectiveInjector_.get (http://localhost:3000/vendor/@angular/core/bundles/core.umd.js:3140:25)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:3000/vendor/@angular/core/bundles/core.umd.js:8996:56)
    at loadModuleFactory (http://localhost:3000/vendor/ui-router-ng2/_bundles/ui-router-ng2.js:8501:28)
    at eval (http://localhost:3000/vendor/ui-router-ng2/_bundles/ui-router-ng2.js:8481:16)
    at lazyLoadState (http://localhost:3000/vendor/ui-router-ng2/_bundles/ui-router-ng2.js:6098:30)
    at eval (http://localhost:3000/vendor/ui-router-ng2/_bundles/ui-router-ng2.js:6069:40)
    at Array.map (native)
    at lazyLoadHook (http://localhost:3000/vendor/ui-router-ng2/_bundles/ui-router-ng2.js:6069:10)
```

I search the github issues and found that somebody reported the similar issue before but type of TransitionRejection is 6 which is different. 

The above lazy loading works well if I use @angular/router but I strongly hope that ui-router-ng2 can support this well too. We built a large angular1 app intensively depending on the ui-router. Now we immigrate to ng2 I do not want to go away from ui-router.

**Comment by christopherthielen** [comment]
Possibly related https://github.com/angular/angular/issues/14343

**Comment by about-code** [comment]
> "No NgModule metadata found for '[object Object]"

In the setup which I had in angular/angular#14343 the part `[object Object]` resolved to a correct module class name. Further I had a pure Angular2 setup with @angular/router and hadn't to use `System.import` myself to load the module.

Given that the error message printed for @lexigren is logged by the same piece of angular code like it is in my case, then the code which produces the message attempts to infer the class name from decorator metadata. If the class name resolves to `[object Object]` in @lexigren's case it may indeed be the case that the result returned by the SystemJS-Promise callback does not match with what angular expects. 

@lexigren If you explore angular/angular#14343 you'll see that what is exported in my case is the result of a `_decorate()`call. Not sure what the value of `result.ProductsModule`is in your case. I guess the issue might be easier to investigate if you could provide the part of *product.module* where the class is decorated and exported as well as your SystemJS Loader config, if that's possible.

**Comment by christopherthielen** [comment]
Lazy loading has changed significantly since this issue was filed.  I don't think the issue is relevant anymore.  If it's still an issue, please let me know and we can reopen.  Please view the [sample app](https://github.com/ui-router/sample-app-angular) for and the [lazy loading guide](https://ui-router.github.io/guide/lazyloading) for current lazy loading practices.
