### ISSUE TITLE
Get error when using "resolve"

### ISSUE THREAD

**Issue by vjcspy** [ui-router/angular#37]
Environment:
- angular 2.4.3
- ui-router: 1.0.0-beta.4

if use resolve, exp:
`resolve: [
  { 
    token: 'people',
    deps: [PeopleService], 
    resolveFn: (peopleSvc) => peopleSvc.getAllPeople()
  }
]`
 will get errors
`Uncaught TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at getParentCtor (http://localhost:8080/vendor.dll.js:60384:47)
    at ReflectionCapabilities.annotations (http://localhost:8080/vendor.dll.js:60241:43)
    at Reflector.annotations (http://localhost:8080/vendor.dll.js:60448:44)
    at DirectiveResolver.isDirective (http://localhost:8080/vendor.dll.js:17086:61)
    at http://localhost:8080/vendor.dll.js:18710:42
    at Array.forEach (native)
    at CompileMetadataResolver._getEntryComponentsFromProvider (http://localhost:8080/vendor.dll.js:18709:30)
    at http://localhost:8080/vendor.dll.js:18682:83
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:8080/vendor.dll.js:18652:19)
    at http://localhost:8080/vendor.dll.js:18259:63
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8080/vendor.dll.js:18250:49)
    at CompileMetadataResolver.getNgModuleSummary (http://localhost:8080/vendor.dll.js:18192:52)
    at http://localhost:8080/vendor.dll.js:18263:72
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8080/vendor.dll.js:18250:49)
    at JitCompiler._loadModules (http://localhost:8080/vendor.dll.js:52289:64)
    at JitCompiler._compileModuleAndComponents (http://localhost:8080/vendor.dll.js:52249:52)
    at JitCompiler.compileModuleAsync (http://localhost:8080/vendor.dll.js:52215:21)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:8080/vendor.dll.js:40098:25)
    at PlatformRef_.bootstrapModule (http://localhost:8080/vendor.dll.js:40073:21)
    at HTMLDocument.main (http://localhost:8080/main.bundle.js:2918:10)
    at ZoneDelegate.invokeTask (http://localhost:8080/polyfills.dll.js:4195:35)
    at Zone.runTask (http://localhost:8080/polyfills.dll.js:4071:47)
    at HTMLDocument.ZoneTask.invoke (http://localhost:8080/polyfills.dll.js:4265:33)`

Pls help !!!

**Comment by christopherthielen** [comment]
I recognize the resolve block from the ui-router tutorials.  It is working in the tutorials (plunker) using SystemJS.  

What is your environment? Are you using the CLI?

Can you try switching to a function and exporting the function?

e.g.:
```js
export function getAllPeople(peopleSvc) { return peopleSvc.getAllPeople(); }
...
resolve: [ { token: 'people', deps: [PeopleService], resolveFn: getAllPeople } ]
```

**Comment by vjcspy** [comment]
That is just an example I get to easily visualize. It is working when i use angular ~2.2 and ui-router 1.0.0-beta.3. After i updated to angular 2.4 and ui-router 1.0.0-beta 4 then the above error happened.
If I try to switch as you said, it worked fine. But i don't know why???
I'm using webpack and tested in fresh project.
Thanks.

**Comment by mfanto** [comment]
I had the same error. It was because I was targeting ES6, not ES5, in my tsconfig.json. Changing to ES5 fixed the error. 

    {
	"compilerOptions": {
		"target": "es5"
        }
    }

**Comment by christopherthielen** [comment]
Hopefully the suggestion above works.  If not, I suggest updating to the latest version of ui-router and angular.  If it's still a problem, please re-open this issue.
