### ISSUE TITLE
Transition Ignored?

### ISSUE THREAD

**Issue by kolkov** [ui-router/angular#58]
Hi! What may causing this problem on prod server?

![image](https://cloud.githubusercontent.com/assets/3740898/23336006/673a8e18-fbd3-11e6-86c1-719acd8ebdbb.png)
one difference base href and port...
prod:
![image](https://cloud.githubusercontent.com/assets/3740898/23336031/f006eb38-fbd3-11e6-9c4f-4dcabfd37ac3.png)
and dev:
![image](https://cloud.githubusercontent.com/assets/3740898/23336035/06f55a96-fbd4-11e6-8299-329d59775fe7.png)

**Comment by kolkov** [comment]
Try to install master from github... but only package.json installed :(
![image](https://cloud.githubusercontent.com/assets/3740898/23338345/7ffbfeaa-fc19-11e6-9e04-6f0a43c267e7.png)

**Comment by kolkov** [comment]
Is the developing instruction valid?
https://github.com/ui-router/ng2/blob/master/CONTRIBUTING.md

**Comment by kolkov** [comment]
```
D:\!Projects\TypeScript\ui-router\ui-router-ng2>npm install
npm WARN update-linked node_modules\ui-router-core needs updating to 4.0.0 from 5.0.0 but we can't, as it's a symlink
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> ui-router-ng2@1.0.0-beta.4 prepublish D:\!Projects\TypeScript\ui-router\ui-router-ng2
> npm run build


> ui-router-ng2@1.0.0-beta.4 build D:\!Projects\TypeScript\ui-router\ui-router-ng2
> npm run compile && npm run bundle


> ui-router-ng2@1.0.0-beta.4 compile D:\!Projects\TypeScript\ui-router\ui-router-ng2
> npm run clean && ngc


> ui-router-ng2@1.0.0-beta.4 clean D:\!Projects\TypeScript\ui-router\ui-router-ng2
> shx rm -rf lib lib-esm _bundles _dec

Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/ui-router-core/lib/resolve/resolveContext.d.ts:7:44: Initializers are not allowed in ambient contexts.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/src/statebuilders/views.ts:2:9: Module '"D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/ui-router-core/lib/index"' has no exported member 'State'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/src/directives/uiView.ts:9:74: Module '"D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/ui-router-core/lib/index"' has no exported member 'State'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/src/directives/uiSrefStatus.ts:6:38: Module '"D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/ui-router-core/lib/index"' has no exported member 'State'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/src/statebuilders/lazyLoad.ts:4:27: Module '"D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/ui-router-core/lib/index"' has no exported member 'State'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/jasmine/index.d.ts:39:38: A parameter initializer is only allowed in a function or constructor implementation.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/jasmine/index.d.ts:39:46: Cannot find name 'keyof'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/jasmine/index.d.ts:39:52: '=' expected.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:244:13: Duplicate identifier '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:244:16: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:246:25: Cannot find name 'Partial'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:248:19: Duplicate identifier '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:366:39: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:2083:24: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5585:44: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5592:44: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5599:44: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5606:44: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5639:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5648:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5655:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5662:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5671:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5678:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5685:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5694:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5701:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5708:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5717:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5724:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:5731:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11444:9: A computed property name must be of type 'string', 'number', 'symbol', or 'any'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11444:10: Cannot find name 'P'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11444:15: Cannot find name 'keyof'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11444:21: ']' expected.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11444:21: Cannot find name 'T'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11444:22: ';' expected.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11444:23: Declaration or statement expected.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11444:26: A parameter initializer is only allowed in a function or constructor implementation.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11444:31: Cannot find name 'T'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11444:33: ']' expected.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11444:34: ')' expected.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11444:35: Declaration or statement expected.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11444:37: Declaration or statement expected.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11444:40: Cannot find name 'boolean'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11453:29: Cannot find name 'ConformsPredicateObject'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:11464:42: Cannot find name 'ConformsPredicateObject'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15394:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15403:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15436:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15445:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15480:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15489:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15522:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15531:12: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15564:22: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15571:22: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15604:24: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15611:24: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15627:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15636:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15646:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15656:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15666:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15676:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15686:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15696:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15731:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15739:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15746:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15778:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15786:21: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15793:21: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15856:21: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15856:37: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:15872:21: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16533:33: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16543:33: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16553:33: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16622:33: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16631:33: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16640:33: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16700:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16709:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16719:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16729:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16739:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16749:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16759:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16769:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16788:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16797:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16806:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16816:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16824:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16834:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16842:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16864:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16874:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16884:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16895:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16904:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16915:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:16924:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:17081:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:17089:21: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:17096:21: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:17112:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:17121:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:17130:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:17139:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:17149:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:17157:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:17167:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:17175:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:17926:39: Cannot find name 'TemplateSettings'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18546:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18554:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18676:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18684:19: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18693:47: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18702:47: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18818:31: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18855:43: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18862:43: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18869:43: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18876:43: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18883:43: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18895:40: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18902:40: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18909:40: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18916:40: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18923:40: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18935:39: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18942:39: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18949:39: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18956:39: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18963:39: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:18974:39: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:19014:53: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:19021:58: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:19028:58: Cannot find name 'Many'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:19188:22: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:19212:22: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:19235:23: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:19258:23: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:19281:21: Cannot find namespace '_'.
Error at D:/!Projects/TypeScript/ui-router/ui-router-ng2/node_modules/@types/lodash/index.d.ts:19441:1: Declaration or statement expected.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Andy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
npm ERR! node v7.5.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ui-router-ng2@1.0.0-beta.4 compile: `npm run clean && ngc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ui-router-ng2@1.0.0-beta.4 compile script 'npm run clean && ngc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ui-router-ng2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && ngc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ui-router-ng2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ui-router-ng2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Andy\AppData\Roaming\npm-cache\_logs\2017-02-26T09_33_43_089Z-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Andy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.5.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ui-router-ng2@1.0.0-beta.4 build: `npm run compile && npm run bundle`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ui-router-ng2@1.0.0-beta.4 build script 'npm run compile && npm run bundle'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ui-router-ng2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile && npm run bundle
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ui-router-ng2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ui-router-ng2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Andy\AppData\Roaming\npm-cache\_logs\2017-02-26T09_33_43_146Z-debug.log

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/core@2.4.8 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@2.4.8 requires a peer of zone.js@^0.7.2 but none was installed.
npm WARN @angular/router@3.4.8 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN ui-router-rx@0.2.1 requires a peer of rxjs@^5.0.3 but none was installed.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Andy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ui-router-ng2@1.0.0-beta.4 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ui-router-ng2@1.0.0-beta.4 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ui-router-ng2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ui-router-ng2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ui-router-ng2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Andy\AppData\Roaming\npm-cache\_logs\2017-02-26T09_33_43_205Z-debug.log

D:\!Projects\TypeScript\ui-router\ui-router-ng2>
```

**Comment by kolkov** [comment]
"@types/lodash": "ts2.0" worked for me

**Comment by mkoczorowski** [comment]
Hi there, 
What is this "@types/lodash": "ts2.2" exactly ? is it an entry in package.json ? "ts.2.2" ?

I ran npm install "@types/lodash" -D
but It created and entry  "@types/lodash": "^4.14.57"

which doesn't solve the problem for me.

Thanks

**Comment by mkoczorowski** [comment]
ah I got it. Upgraded typescript to 2.2.1 and it worked.
Thanks a lot for the hint
